---
kind: pipeline
name: default

steps:
  - name: overlee
    image: rust:1.51.0
    environment:
      RUST_BACKTRACE: full
    commands:
      - rustup component add rustfmt clippy
      - rustc --version
      - cargo clippy --version
      - cargo fmt --version
      - cargo fmt -- --check
      - cargo clippy --workspace
      - cargo test --workspace
