kind: pipeline
name: default

steps:
- name: overlee
  image: rust:1.47.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustc --version
  - rustup component add rustfmt clippy
  - cargo fmt -- --check
  - cargo clippy --workspace
  - cargo test --workspace
